climate:
  - platform: tasmota_irhvac
    name: "EDIT1" #ตั้งชื่อ Climate Entity
    command_topic: "cmnd/EDIT2/IRHvac" #ชื่อจาก Topic หน้า MQTT Config
    state_topic: "stat/EDIT3/RESULT" #ชื่อจาก Topic หน้า MQTT Config
    temperature_sensor: sensor.rockubox_bmp280_temperature #Temp Entity
    protocol: "DAIKIN" #เลือก Protocol จากรายการด้านหลัง , DAIKIN , MITSUBISHI_AC, GREE, TOSHIBA_AC, FUJITSU_AC, MIDEA, HAIER_AC, HITACHI_AC, HAIER_AC_YRW02, WHIRLPOOL_AC, SAMSUNG_AC, PANASONIC_AC, DAIKIN2, MITSUBISHI_HEAVY_88, MITSUBISHI_HEAVY_152, DAIKIN216, SHARP_AC, DAIKIN160, DAIKIN176, DAIKIN128
    min_temp: 18 #อุณหภูมิต่ำสุดที่แอร์ทำได้
    max_temp: 32 #อุณหภูมิสูงสุดที่แอร์ทำได้
    target_temp: 26 #อุณหภูมิค่ามาตรฐาน
    initial_operation_mode: "off" #กรณีที่ตัวอุปกรณ์ Reboot ให้คงสถานะปิดไม่แนะนำให้เลือก Cool หากเกิดกรณี แอร์ติดเองให้ติดต่อลุงร๊อค
    precision: 1.0 #ระดับสำหับการปรับอุณหภูมิ
    supported_modes:
      - cool
      - dry
      - fan_only
      #- auto
      - "off"
    supported_fan_speeds:
      - low
      - middle
      - medium
      - high
      - max
      - auto
    supported_swing_list: #เลือกโหมดการส่ายถ้ามี
      - "off"
      - vertical
      #- horizontal
      #- both
    hvac_model: "-1"
    celsius_mode: "On"
